### ISSUE TITLE
插件查找失败

### ISSUE THREAD

**Issue by swpfY** [SwanHubX/req-preprocess#13]
```bash
traefik-reverse-proxy-1  | time="2023-11-23T14:08:36Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
traefik-reverse-proxy-1  | time="2023-11-23T14:08:36Z" level=error msg="plugin: unknown plugin type: hello" entryPointName=http routerName=my-router@file
```
`Provider` 为配置文件，分为静态配置部分和动态配置部分。将插件部分配置放置在了动态配置部分:
```yaml
experimental:
  localPlugins:
    hello:
      moduleName: github.com/SwanHubX/req-preprocess
```
